# Generated by Django 5.2.5 on 2025-09-01 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, max_length=128)),
                ('invoice_date', models.DateField(blank=True, db_index=True, null=True)),
                ('currency', models.CharField(default='ARS', max_length=8)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('total_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('blob_url', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_tax_id', models.CharField(blank=True, max_length=64, null=True)),
                ('payment_term', models.CharField(blank=True, max_length=100, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('service_start_date', models.DateField(blank=True, null=True)),
                ('service_end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(db_index=True, max_length=512)),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('unit', models.CharField(blank=True, max_length=32, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('line_total', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('product_code', models.CharField(blank=True, max_length=128, null=True)),
                ('item_date', models.DateField(blank=True, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('tax_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('name', 'tax_id')},
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='invoices.supplier'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_date'], name='invoices_in_invoice_087f87_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('supplier', 'invoice_number')},
        ),
    ]
