# Generated by Django 5.2.5 on 2025-10-16 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CondicionIVA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Condición frente al IVA',
                'verbose_name_plural': 'Condiciones frente al IVA',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CondicionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('dias', models.PositiveIntegerField(default=0, help_text='Días de crédito (0 = contado)')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Condición de pago',
                'verbose_name_plural': 'Condiciones de pago',
                'ordering': ['dias', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ItemFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_producto', models.CharField(blank=True, max_length=64, null=True)),
                ('cantidad', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('unidad', models.CharField(blank=True, max_length=20, null=True)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('importe', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('alic_iva', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Alicuota IVA (%)')),
                ('codigo_fiscal', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código ARCA / fiscal')),
                ('tipo_item', models.CharField(choices=[('producto', 'producto/servicio'), ('impuesto', 'Impuesto/Retención'), ('resumen', 'Subtotal/Total')], default='producto', max_length=20)),
            ],
            options={
                'verbose_name': 'Ítem de factura',
                'verbose_name_plural': 'Ítems de factura',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TipoComprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3, unique=True)),
                ('descripcion', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de comprobante',
                'verbose_name_plural': 'Tipos de comprobante',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punto_venta', models.CharField(blank=True, max_length=5, null=True)),
                ('numero', models.CharField(blank=True, max_length=128, null=True)),
                ('cae', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código de autorización fiscal (ARCA)')),
                ('vto_cae', models.DateField(blank=True, null=True, verbose_name='Vencimiento CAE')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('moneda', models.CharField(default='ARS', max_length=10)),
                ('tipo_cambio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_impuestos', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cliente_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('cliente_id_fiscal', models.CharField(blank=True, max_length=20, null=True)),
                ('cliente_direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('servicio_desde', models.DateField(blank=True, null=True)),
                ('servicio_hasta', models.DateField(blank=True, null=True)),
                ('vencimiento', models.DateField(blank=True, null=True)),
                ('url_blob', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condicion_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.condicionpago')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
