# Generated by Django 5.2.5 on 2025-10-11 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CondicionIVA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Condición frente al IVA',
                'verbose_name_plural': 'Condiciones frente al IVA',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CondicionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('dias', models.PositiveIntegerField(default=0, help_text='Días de crédito (0 = contado)')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Condición de pago',
                'verbose_name_plural': 'Condiciones de pago',
                'ordering': ['dias', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoComprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3, unique=True)),
                ('descripcion', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de comprobante',
                'verbose_name_plural': 'Tipos de comprobante',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('codigo_interno', models.CharField(blank=True, max_length=64, null=True)),
                ('codigo_proveedor', models.CharField(blank=True, max_length=64, null=True)),
                ('codigo_barras', models.CharField(blank=True, max_length=64, null=True)),
                ('categoria', models.CharField(blank=True, max_length=128, null=True)),
                ('marca', models.CharField(blank=True, max_length=128, null=True)),
                ('unidad_base', models.CharField(blank=True, max_length=20, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['codigo_interno'], name='invoices_pr_codigo__f2d6f6_idx'), models.Index(fields=['codigo_proveedor'], name='invoices_pr_codigo__07c743_idx'), models.Index(fields=['codigo_barras'], name='invoices_pr_codigo__e2433e_idx'), models.Index(fields=['nombre'], name='invoices_pr_nombre_fc0ae9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('id_fiscal', models.CharField(blank=True, max_length=20, null=True, verbose_name='CUIT / ID Fiscal')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('condicion_iva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.condicioniva')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
                'unique_together': {('nombre', 'id_fiscal')},
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punto_venta', models.CharField(blank=True, max_length=5, null=True)),
                ('numero', models.CharField(blank=True, max_length=128, null=True)),
                ('cae', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código de autorización fiscal (ARCA)')),
                ('vto_cae', models.DateField(blank=True, null=True, verbose_name='Vencimiento CAE')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('moneda', models.CharField(default='ARS', max_length=10)),
                ('tipo_cambio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_impuestos', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cliente_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('cliente_id_fiscal', models.CharField(blank=True, max_length=20, null=True)),
                ('cliente_direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('servicio_desde', models.DateField(blank=True, null=True)),
                ('servicio_hasta', models.DateField(blank=True, null=True)),
                ('vencimiento', models.DateField(blank=True, null=True)),
                ('url_blob', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condicion_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.condicionpago')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_creadas', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_editadas', to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='invoices.proveedor')),
                ('tipo_comprobante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.tipocomprobante')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ItemFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_producto', models.CharField(blank=True, max_length=64, null=True)),
                ('cantidad', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('unidad', models.CharField(blank=True, max_length=20, null=True)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('importe', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('alic_iva', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Alicuota IVA (%)')),
                ('codigo_fiscal', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código ARCA / fiscal')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.factura')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.producto')),
            ],
            options={
                'verbose_name': 'Ítem de factura',
                'verbose_name_plural': 'Ítems de factura',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['codigo_producto'], name='invoices_it_codigo__d0e27b_idx'), models.Index(fields=['descripcion'], name='invoices_it_descrip_b7ca9f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['fecha'], name='invoices_fa_fecha_651924_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['numero'], name='invoices_fa_numero_067770_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['tipo_comprobante', 'punto_venta'], name='invoices_fa_tipo_co_865959_idx'),
        ),
    ]
