# Generated by Django 5.2.5 on 2025-10-16 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices', '0001_initial'),
        ('productos', '0001_initial'),
        ('proveedores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='proveedores.proveedor'),
        ),
        migrations.AddField(
            model_name='factura',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_editadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemfactura',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.factura'),
        ),
        migrations.AddField(
            model_name='itemfactura',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.producto'),
        ),
        migrations.AddField(
            model_name='factura',
            name='tipo_comprobante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.tipocomprobante'),
        ),
        migrations.AddIndex(
            model_name='itemfactura',
            index=models.Index(fields=['codigo_producto'], name='invoices_it_codigo__d0e27b_idx'),
        ),
        migrations.AddIndex(
            model_name='itemfactura',
            index=models.Index(fields=['descripcion'], name='invoices_it_descrip_b7ca9f_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['fecha'], name='invoices_fa_fecha_651924_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['numero'], name='invoices_fa_numero_067770_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['tipo_comprobante', 'punto_venta'], name='invoices_fa_tipo_co_865959_idx'),
        ),
    ]
