# Generated by Django 5.2.5 on 2025-10-14 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemfactura',
            name='tipo_item',
            field=models.CharField(choices=[('producto', 'producto/servicio'), ('impuesto', 'Impuesto/Retención'), ('resumen', 'Subtotal/Total')], default='producto', max_length=20),
        ),
    ]
