# Generated by Django 5.2.5 on 2025-09-04 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='customer_adress',
            field=models.TextField(blank=True, null=True),
        ),
    ]
