# Generated by Django 5.2.5 on 2025-09-04 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoice_customer_adress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='customer_adress',
            new_name='customer_address',
        ),
    ]
