# Generated by Django 5.2.5 on 2025-11-06 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_initial'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='factura',
            unique_together={('proveedor', 'tipo_comprobante', 'punto_venta', 'numero')},
        ),
    ]
