# Generated by Django 5.2.5 on 2025-09-19 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_rename_customer_adress_invoice_customer_address'),
    ]

    operations = [
        # Modelos
        migrations.RenameModel('Supplier', 'Proveedor'),
        migrations.RenameModel('Invoice', 'Factura'),
        migrations.RenameModel('InvoiceItem', 'ItemFactura'),

        # Campos de Supplier -> Proveedor
        migrations.RenameField('Proveedor', 'name', 'nombre'),
        migrations.RenameField('Proveedor', 'tax_id', 'id_fiscal'),
        migrations.RenameField('Proveedor', 'address', 'direccion'),

        # Campos de Invoice -> Factura
        migrations.RenameField('Factura', 'supplier', 'proveedor'),
        migrations.RenameField('Factura', 'invoice_number', 'numero'),
        migrations.RenameField('Factura', 'invoice_date', 'fecha'),
        migrations.RenameField('Factura', 'currency', 'moneda'),
        migrations.RenameField('Factura', 'subtotal', 'subtotal'),
        migrations.RenameField('Factura', 'total_tax', 'total_impuestos'),
        migrations.RenameField('Factura', 'total', 'total'),
        migrations.RenameField('Factura', 'blob_url', 'url_blob'),
        migrations.RenameField('Factura', 'created_at', 'creado_en'),

        migrations.RenameField('Factura', 'customer_name', 'cliente_nombre'),
        migrations.RenameField('Factura', 'customer_tax_id', 'cliente_id_fiscal'),
        migrations.RenameField('Factura', 'customer_address', 'cliente_direccion'),
        migrations.RenameField('Factura', 'payment_term', 'condicion_pago'),
        migrations.RenameField('Factura', 'due_date', 'vencimiento'),
        migrations.RenameField('Factura', 'service_start_date', 'servicio_desde'),
        migrations.RenameField('Factura', 'service_end_date', 'servicio_hasta'),

        # Campos de InvoiceItem -> ItemFactura
        migrations.RenameField('ItemFactura', 'invoice', 'factura'),
        migrations.RenameField('ItemFactura', 'product_name', 'descripcion'),
        migrations.RenameField('ItemFactura', 'quantity', 'cantidad'),
        migrations.RenameField('ItemFactura', 'unit', 'unidad'),
        migrations.RenameField('ItemFactura', 'unit_price', 'precio_unitario'),
        migrations.RenameField('ItemFactura', 'line_total', 'importe'),
        migrations.RenameField('ItemFactura', 'product_code', 'codigo_producto'),
        migrations.RenameField('ItemFactura', 'item_date', 'fecha_item'),
    ]