# Generated by Django 5.2.5 on 2025-10-08 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_factura_alter_invoice_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factura',
            options={'verbose_name': 'Factura', 'verbose_name_plural': 'Facturas'},
        ),
        migrations.AlterModelOptions(
            name='itemfactura',
            options={'verbose_name': 'Ítem de factura', 'verbose_name_plural': 'Ítems de factura'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.RemoveIndex(
            model_name='factura',
            name='invoices_in_invoice_087f87_idx',
        ),
        migrations.AlterField(
            model_name='factura',
            name='cliente_direccion',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección del cliente'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='cliente_id_fiscal',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='ID fiscal del cliente'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='cliente_nombre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del cliente'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='condicion_pago',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Condición de pago'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado en'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Fecha de factura'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='moneda',
            field=models.CharField(default='ARS', max_length=8, verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='numero',
            field=models.CharField(db_index=True, max_length=128, verbose_name='Número de factura'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='invoices.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='servicio_desde',
            field=models.DateField(blank=True, null=True, verbose_name='Servicio desde'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='servicio_hasta',
            field=models.DateField(blank=True, null=True, verbose_name='Servicio hasta'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='total_impuestos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Total impuestos'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='url_blob',
            field=models.TextField(verbose_name='URL del blob'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimiento'),
        ),
        migrations.AlterField(
            model_name='itemfactura',
            name='cantidad',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='itemfactura',
            name='codigo_producto',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Código de producto'),
        ),
        migrations.AlterField(
            model_name='itemfactura',
            name='descripcion',
            field=models.CharField(db_index=True, max_length=512, verbose_name='Descripción del producto/servicio'),
        ),
        migrations.AlterField(
            model_name='itemfactura',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.factura', verbose_name='Factura'),
        ),
        migrations.AlterField(
            model_name='itemfactura',
            name='fecha_item',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha del ítem'),
        ),
        migrations.AlterField(
            model_name='itemfactura',
            name='importe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Importe (línea)'),
        ),
        migrations.AlterField(
            model_name='itemfactura',
            name='precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='Precio unitario'),
        ),
        migrations.AlterField(
            model_name='itemfactura',
            name='unidad',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Unidad'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='id_fiscal',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='ID fiscal / CUIT'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Nombre'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['fecha'], name='invoices_fa_fecha_651924_idx'),
        ),
    ]
