# Generated by Django 5.2.5 on 2025-10-16 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('codigo_interno', models.CharField(blank=True, max_length=64, null=True)),
                ('codigo_proveedor', models.CharField(blank=True, max_length=64, null=True)),
                ('codigo_barras', models.CharField(blank=True, max_length=64, null=True)),
                ('categoria', models.CharField(blank=True, max_length=128, null=True)),
                ('marca', models.CharField(blank=True, max_length=128, null=True)),
                ('unidad_base', models.CharField(blank=True, max_length=20, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['codigo_interno'], name='productos_p_codigo__b937f5_idx'), models.Index(fields=['codigo_proveedor'], name='productos_p_codigo__fa28b7_idx'), models.Index(fields=['codigo_barras'], name='productos_p_codigo__7c1f60_idx'), models.Index(fields=['nombre'], name='productos_p_nombre_456643_idx')],
            },
        ),
    ]
