# Generated by Django 5.2.5 on 2025-11-10 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_productoembedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoembedding',
            name='vector',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
